name: Deploy Python Code
on: [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy Python files
        uses: appleboy/scp-action@v0.1.7
        with:
            host: ${{ secrets.VM_HOST }}
            username: ubuntu
            key: ${{ secrets.VM_KEY }}
            port: 22
            source: "./main.py,./requirements.txt"
            target: /home/ubuntu

      - name: Install Python dependencies and run script
        uses: appleboy/ssh-action@v1.2.0
        with:
            host: ${{ secrets.VM_HOST }}
            username: ubuntu
            key: ${{ secrets.VM_KEY }}
            port: 22
            script: |
                pip3 install flask --break-system-packages
                nohup python3 main.py > output.log 2>&1 &
      - name: Super-linter
        uses: super-linter/super-linter@v7.2.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          

    

